apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-core-app
  namespace: {{ blue_green }}
  labels:
    app: auth-core-app
spec:
  selector:
    matchLabels:
      app: auth-core-app
  replicas: 1
  minReadySeconds: 30
  strategy:
    rollingUpdate:
      maxSurge: 3
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth-core-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: region
                operator: In
                values:
                - {{ POD_AFFINITY }}
      containers:
      - name: auth-core-app-container
        imagePullPolicy: Always
        image: {{ IMAGE_AUTH_CORE }}
        env:
         - name: APP_CONT
           value: {{ CONT_AUTH }}
        envFrom:
        - configMapRef:
            name: puc
        ports:
          - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: auth-core-app-service
  namespace: {{ blue_green }}
  labels:
    app: auth-core-app
spec:
  ports:
    - name: http
      port: 8080
  selector:
    app: auth-core-app
  type: ClusterIP 
