-- MySQL Script generated by MySQL Workbench
-- ter 20 jul 2021 20:32:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pucmg
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pucmg
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pucmg` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pucmg` ;

-- -----------------------------------------------------
-- Table `pucmg`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`status` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`status` (
  `id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`role` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`role` (
  `id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`usuario` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`usuario` (
  `id` BIGINT NOT NULL,
  `codigo` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `nome` VARCHAR(255) NULL DEFAULT NULL,
  `role_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuario_role1_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_role1`
    FOREIGN KEY (`role_id`)
    REFERENCES `pucmg`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`projeto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`projeto` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`projeto` (
  `id` BIGINT NOT NULL,
  `inicio` TIMESTAMP NULL DEFAULT NULL,
  `cor` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `fim` TIMESTAMP NULL DEFAULT NULL,
  `identificacao` VARCHAR(255) NULL DEFAULT NULL,
  `status_id` BIGINT NOT NULL,
  `manager_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projeto_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_projeto_usuario1_idx` (`manager_id` ASC) VISIBLE,
  CONSTRAINT `fk_projeto_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `pucmg`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_usuario1`
    FOREIGN KEY (`manager_id`)
    REFERENCES `pucmg`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`atividade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`atividade` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`atividade` (
  `id` BIGINT NOT NULL,
  `inicio` TIMESTAMP NULL DEFAULT NULL,
  `cor` VARCHAR(255) NULL DEFAULT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `fim` TIMESTAMP NULL DEFAULT NULL,
  `associate_id` BIGINT NULL DEFAULT NULL,
  `status_id` BIGINT NOT NULL,
  `projeto_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atividade_status1_idx` (`status_id` ASC) VISIBLE,
  INDEX `fk_atividade_projeto1_idx` (`projeto_id` ASC) VISIBLE,
  CONSTRAINT `fk_atividade_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `pucmg`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_atividade_projeto1`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `pucmg`.`projeto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`fase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`fase` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`fase` (
  `id` BIGINT NOT NULL,
  `inicio` TIMESTAMP NULL DEFAULT NULL,
  `cor` VARCHAR(255) NULL DEFAULT NULL,
  `fim` TIMESTAMP NULL DEFAULT NULL,
  `sequencia` BIGINT NULL DEFAULT NULL,
  `phase_type_id` BIGINT NULL DEFAULT NULL,
  `project_id` BIGINT NULL DEFAULT NULL,
  `status_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fase_status1_idx` (`status_id` ASC) VISIBLE,
  CONSTRAINT `fk_fase_status1`
    FOREIGN KEY (`status_id`)
    REFERENCES `pucmg`.`status` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`fase_activities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`fase_activities` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`fase_activities` (
  `id` INT NOT NULL,
  `fase_id` BIGINT NOT NULL,
  `atividade_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_fase_activities_fase1_idx` (`fase_id` ASC) VISIBLE,
  INDEX `fk_fase_activities_atividade1_idx` (`atividade_id` ASC) VISIBLE,
  CONSTRAINT `fk_fase_activities_fase1`
    FOREIGN KEY (`fase_id`)
    REFERENCES `pucmg`.`fase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_fase_activities_atividade1`
    FOREIGN KEY (`atividade_id`)
    REFERENCES `pucmg`.`atividade` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`projeto_associates`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`projeto_associates` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`projeto_associates` (
  `id` INT NOT NULL,
  `projeto_id` BIGINT NOT NULL,
  `associate_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_projeto_associates_projeto1_idx` (`projeto_id` ASC) VISIBLE,
  INDEX `fk_projeto_associates_usuario1_idx` (`associate_id` ASC) VISIBLE,
  CONSTRAINT `fk_projeto_associates_projeto1`
    FOREIGN KEY (`projeto_id`)
    REFERENCES `pucmg`.`projeto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_projeto_associates_usuario1`
    FOREIGN KEY (`associate_id`)
    REFERENCES `pucmg`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`tipofase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`tipofase` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`tipofase` (
  `id` BIGINT NOT NULL,
  `descricao` VARCHAR(255) NULL DEFAULT NULL,
  `fase_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tipofase_fase_idx` (`fase_id` ASC) VISIBLE,
  CONSTRAINT `fk_tipofase_fase`
    FOREIGN KEY (`fase_id`)
    REFERENCES `pucmg`.`fase` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`notificacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`notificacao` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`notificacao` (
  `id` BIGINT NOT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `parametros` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pucmg`.`relatorio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pucmg`.`relatorio` ;

CREATE TABLE IF NOT EXISTS `pucmg`.`relatorio` (
  `id` BIGINT NOT NULL,
  `tipo` VARCHAR(255) NULL DEFAULT NULL,
  `parametros` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
